import React from "react";

import Autocomplete from "./Autocomplete";

function LocationsAutocomplete() {
    return (
        <Autocomplete
                suggestions={[
                        "Helsinki Keskusta - Etu-Töölö",
                        "Punavuori",
                        "Kaartinkaupunki",
                        "Kaivopuisto - Ullanlinna",
                        "Eira - Hernesaari",
                        "Katajanokka",
                        "Kruununhaka",
                        "Kamppi - Ruoholahti",
                        "Suomenlinna",
                        "Lauttasaari",
                        "Vattuniemi",
                        "Jätkäsaari",
                        "Ilmala",
                        "Länsi-Pasila",
                        "Taka-Töölö",
                        "Keski-Töölö",
                        "Pohjois-Meilahti",
                        "Ruskeasuo",
                        "Meilahden sairaala-alue",
                        "Pikku Huopalahti",
                        "Kivihaka",
                        "Etelä-Haaga",
                        "Munkkiniemi",
                        "Kuusisaari-Lehtisaari",
                        "Munkkivuori-Niemenmäki",
                        "Pajamäki",
                        "Reimarla",
                        "Pitäjänmäen teollisuusalue",
                        "Konala",
                        "Pohjois-Haaga",
                        "Malminkartano",
                        "Kannelmäki",
                        "Maununneva",
                        "Lassila",
                        "Sörnäinen",
                        "Etu-Vallila - Alppila",
                        "Itä-Pasila",
                        "Kallio",
                        "Kalasatama",
                        "Vallila",
                        "Toukola-Vanhakaupunki",
                        "Kulosaari",
                        "Verkkosaari",
                        "Kaitalahti",
                        "Koskela-Helsinki",
                        "Käpylä",
                        "Metsälä-Etelä-Oulunkylä",
                        "Maunula-Suursuo",
                        "Oulunkylä-Patola",
                        "Veräjämäki",
                        "Länsi-Pakila",
                        "Paloheinä",
                        "Itä-Pakila",
                        "Tuomarinkylä-Torppar",
                        "Malmi",
                        "Pihlajamäki",
                        "Pukinmäki-Savela",
                        "Tapanila",
                        "Siltamäki",
                        "Puistola",
                        "Suurmetsä",
                        "Jakomäki - Alppikylä",
                        "Tapaninvainio",
                        "Viikki",
                        "Länsi-Herttoniemi",
                        "Herttoniemi",
                        "Roihuvuori",
                        "Tammisalo",
                        "Laajasalo",
                        "Jollas",
                        "Santahamina",
                        "Etelä-Laajasalo",
                        "Roihupellon teollisuusalue",
                        "Itäsalmi",
                        "Puotinharju",
                        "Puotila",
                        "Myllypuro",
                        "Itäkeskus-Marjaniemi",
                        "Kontula - Vesala",
                        "Vartioharju",
                        "Pohjois-Vuosaari",
                        "Mellunmäki",
                        "Etelä-Vuosaari",
                        "Aurinkolahti",
                        "Hakunila",
                        "Vaarala",
                        "Itä-Hakkila",
                        "Länsimäki",
                        "Tikkurila",
                        "Leinelä",
                        "Hiekkaharju",
                        "Koivukylä-Havukoski",
                        "Jokiniemi",
                        "Kuusikko-Hakkila",
                        "Ruskeasanta-Ilola",
                        "Rekola",
                        "Päiväkumpu",
                        "Korso",
                        "Mikkola",
                        "Nikinmäki",
                        "Kirkonkylä-Veromäki",
                        "Tammisto",
                        "Veromiehenkylä",
                        "Myyrmäki",
                        "Kaivoksela",
                        "Martinlaakso",
                        "Hämeenkylä",
                        "Hämevaara",
                        "Vapaala",
                        "Varisto",
                        "Vantaanlaakso",
                        "Askisto",
                        "Ylästö",
                        "Kivistö",
                        "Pähkinärinne",
                        "Petikko",
                        "Vantaanpuisto",
                        "Tuupakan teollisuusalue",
                        "Keimola",
                        "Seutula",
                        "Martinlaakson teollisuusalue",
                        "Klaukkala Keskus",
                        "Tapiola",
                        "Otsolahti",
                        "Länsikorkee-Hakaleht",
                        "Pohjois-Tapiola",
                        "Laajalahti-Friisinmäki",
                        "Otaniemi",
                        "Westend",
                        "Haukilahti",
                        "Mankkaa",
                        "Niittykumpu",
                        "Olari-Kuitinmäki",
                        "Matinkylä",
                        "Friisilä",
                        "Henttaa",
                        "Iivisniemi",
                        "Suomenoja",
                        "Puolarmetsä",
                        "Puolarmetsän sairaala",
                        "Nöykkiö",
                        "Kivenlahti",
                        "Kattilalaakso",
                        "Latokaski",
                        "Espoonlahti",
                        "Suvisaaristo",
                        "Oitmäki",
                        "Etelä-Leppävaara",
                        "Kilo",
                        "Karakallio",
                        "Nihtisilta",
                        "Pohjois-Leppävaara",
                        "Lintuvaara",
                        "Uusmäki",
                        "Suur-Kauniainen",
                        "Viherlaakso",
                        "Laaksolahti-Lähderanta",
                        "Laaksolahti",
                        "Karvasmäki-Kunnarla",
                        "Sepänkylä",
                        "Espoon Keskus Itäinen",
                        "Espoon Keskus Läntinen",
                        "Kauklahti",
                        "Kumpyöli-Karhusuo",
                        "Nupuri-Nuuksio",
                        "Siikajärvi",
                        "Niipperi",
                        "Lippajärvi",
                        "Kalajärvi",
                        "Lakisto",
                        "Savio",
                        "Riihikallio"
                ]}
            />
        );
}


export default LocationsAutocomplete;